### ISSUE TITLE
The calculation of Pe  is different with paper

### ISSUE THREAD

**Issue by andy910389** [chihfanhsu/gaze_correction#14]
Hi, I found the calculation of Pe is different with paper, as the following:

self.Pe[0] = -np.abs(self.Pe[2])*(R_le[0]+R_re[0]-size_video[0])/(2*self.f) + self.Pc[0]
self.Pe[1] = np.abs(self.Pe[2])*(R_le[1]+R_re[1]-size_video[1])/(2*self.f) + self.Pc[1]

In the paper, you just  use R_le[0]+R_re[0], but you subtract size_video[0]) in the code.
is it wrong?

Thanks.

**Comment by chihfanhsu** [comment]
Since the coordinates of the eyes detected from the OpenCV is based on the left-top origin, both R_le[0] and R_re[0] should be subtracted by 0.5*size_video[0] to move the origin from the left-top corner to the image center.
So, the corrdinates of the eyes should be fixed by (R_le[0] - 0.5*size_video[0])+(R_re[0]- 0.5*size_video[0]) = R_le[0] +R_re[0] -  size_video[0].

**Comment by andy910389** [comment]
> Since the coordinates of the eyes detected from the OpenCV is based on the left-top origin, both R_le[0] and R_re[0] should be subtracted by 0.5_size_video[0] to move the origin from the left-top corner to the image center. So, the corrdinates of the eyes should be fixed by (R_le[0] - 0.5_size_video[0])+(R_re[0]- 0.5*size_video[0]) = R_le[0] +R_re[0] - size_video[0].

Thank your for reply.
