### ISSUE TITLE
ImportError: You need to first `import keras` in order to use `keras_applications`.

### ISSUE THREAD

**Issue by doczoidberg** [chihfanhsu/gaze_correction#5]
Hi,
great work but code does not work for me:
```
python .\regz_socket_MP_FD.py
Traceback (most recent call last):
  File ".\regz_socket_MP_FD.py", line 16, in <module>
    import tensorflow as tf
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "C:\Python36\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Python36\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python36\lib\site-packages\tensorflow_core\python\__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "C:\Python36\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 26, in <module>
    from tensorflow.python.keras import activations
  File "C:\Python36\lib\site-packages\tensorflow_core\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import applications
  File "C:\Python36\lib\site-packages\tensorflow_core\python\keras\applications\__init__.py", line 53, in <module>
    from tensorflow.python.keras.applications.densenet import DenseNet121
  File "C:\Python36\lib\site-packages\tensorflow_core\python\keras\applications\densenet.py", line 22, in <module>
    from keras_applications import densenet
  File "C:\Python36\lib\site-packages\keras_applications\densenet.py", line 23, in <module>
    backend = get_keras_submodule('backend')
  File "C:\Python36\lib\site-packages\keras_applications\__init__.py", line 39, in get_keras_submodule
    raise ImportError('You need to first `import keras` '
ImportError: You need to first `import keras` in order to use `keras_applications`.
```

**Comment by chihfanhsu** [comment]
Thanks for your interesting in my work.

I think this is caused by the wrong Tensorflow version. What is your TensorFlow version?

Tensorflow 1.8.0 is not binding with Keras yet.

**Comment by doczoidberg** [comment]
that helped, thanks. Do you think that there will be a version without calibration so that different people can use it in an photo booth?

**Comment by chihfanhsu** [comment]
It will be great! I think this feature before. I think it can be auto-estimated by a camera or multiple cameras in a fixed environment. This is in my pending list, I think I will look into this in the future.

**Comment by prabhav05** [comment]
> Thanks for your interesting in my work.
> 
> I think this is caused by the wrong Tensorflow version. What is your TensorFlow version?
> 
> Tensorflow 1.8.0 is not binding with Keras yet.

i am using tensorflow version 2.2.0,still i am having same issue

**Comment by Lukious** [comment]
Hi, I have spent quite a lot of time-solving this problem.

The problem was in keras_applications.

There is two possible way to face this error message:
1. When the keras_applications library version is too old
2. When keras_applications are new but having trouble with TensorFlow's keras_preprocessing library

Anyway it occurred by .json file we can solve this problem by reinstalling Tensorflow and Keras-related things but I know that this works heavily stressful.

This is my personal recommendation for this kind of errors.

1. If you are sure that you installed Keras perfectly then just skipping its check process of Keras backend.

First, find your path of 'keras_applications' are installed (It might be in such 'C:\ProgramData\Anaconda3\Lib\site-packages' Or, just use 'pip show keras_applications')

And then, open (imagenet_utils.py) than edit it like this

 ```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import keras
import json
import warnings
import numpy as np
from . import get_keras_submodule
from . import set_keras_submodules


backend = set_keras_submodules('backend')
backed = 'backend'
keras_utils = get_keras_submodule('utils')

CLASS_INDEX = None
CLASS_INDEX_PATH = ('https://s3.amazonaws.com/deep-learning-models/'
                    'image-models/imagenet_class_index.json')

# Global tensor of imagenet means for preprocessing symbolic inputs
_IMAGENET_MEAN = None

...
 ```

It's just editing check flag rightly (It should be checked by Keras backend API but because of version issue it impossible to check automatically sometimes). 

 2. This is possibly happening with the 'keras_preprocessing' library for the recent version (because some parts of  'keras_applications' are moved to 'keras_preprocessing) in this case you should edit the same parts on 'keras_preprocessing'
 
I know that this is not a perfect solution for the code, But it works okay temporarily.
(But I still highly recommend resetting your env..!)

**Comment by chihfanhsu** [comment]
Great! Thanks for the wonderful solution :D

Since the code does not involve the Keras, it can be simply solved by installing a compatible version of Keras.
